### ISSUE TITLE
Update the Sensu Catalog README with the Sensu Integration specification

### ISSUE THREAD

**Issue by calebhailey** [sensu/catalog#52]
Document the Sensu Integration specification, including the integration directory structure and new `sensu-integration.yaml` resource. 

**Directory structure** 

```
integrations/
└── <service; e.g. "nginx">/
    └── <integration; e.g. "nginx-healthcheck">/
        ├── CHANGELOG.md
        ├── README.md
        ├── logo.png
        ├── sensu-integration.yaml
        └── sensu-resources.yaml
```

* `sensu-integration.yaml` (required) 

  Integration metadata properties. See below RE: Sensu Integration YAML specification. 

* `sensu-resources.yaml` (required)

  Valid Sensu Go resource definitions (e.g. checks, handlers, assets, etc), preferably in YAML format. 

* `logo.png` (required)

   Integration logo in PNG format. 

* `README.md` (required)

   Integration description and setup instructions (if required) in Markdown format (embedded HTML is not supported). 

* `CHANGELOG.md` (optional)

   Recommended but not currently used by the Sensu Catalog Browser (UI). 

**Sensu Integration YAML specification** 

```yaml
---
api_version: catalog/v1
type: Integration 
metadata:
  namespace: sensu
  name: nginx-healthcheck
spec:
  class: "supported"
  provider: "agent/check"
  short_description: "NGINX monitoring"
  supported_platforms: 
  - linux
  - windows
  - darwin
  tags:
  - http
  - nginx
  - webserver 
  contributors:
  - @calebhailey 
  - @jspaleta 
  - @thoward 
 prompts:
  - var: check_name
    type: string
    prompt: "Check Name"
    default: nginx-healthcheck
  - var: url
    type: string
    prompt: "Default URL"
    default: "http://localhost:80/nginx_status"
  - var: interval
    type: int
    prompt: "How often do you want to check X?"
    default: 30
  resource_updates:
  - type: CheckConfig
    api_version: core/v2
    name: nginx-healthcheck
    fields:
    - name: metadata.name
      action: replace
      value: check_name
    - name: spec.interval
      action: replace
      value: interval
    - name: spec.command
      action: replace
      template: >-
        check-nginx-status.rb
        --url {{ .annotations.check_nginx_status_url | default "[[url]]" }}
```
