### ISSUE TITLE
Add a "helloworld" integration template including README and sensu-integration.yaml

### ISSUE THREAD

**Issue by calebhailey** [sensu/catalog#53]
See #52 

- [x] Create a new directory at `integrations/example/helloworld`
- [x] Create a template `README.md` at `integrations/example/helloworld/README.md` with the following outline: 

  ```
  ## Description 
  
  ## Supported Dashboards 

  ## Setup 

  ## Plugins 
  ```

- [x] Create a template `sensu-integration.yaml` at `integrations/example/helloworld/sensu-integration.yaml` with the following contents: 

  ```yaml
  ---
  api_version: v1
  type: Integration
  metadata:
    namespace: sensu
    name: helloworld
  spec: 
    class: community
    provider: agent/check
    short_description: Example Sensu Integration
    supported_platforms: 
    - linux
    - windows
    - darwin
    tags:
    - example
    - helloworld
    contributors:
    - "@calebhailey"
    - "@jsplata"
    prompts:
    - var: integration_name
      type: string
      prompt: "Integration Name"
      default: helloworld
    - var: integration_interval
      type: int
      prompt: "How often do you want to perform this healthcheck?"
      default: 30
    - var: integration_world
      type: int
      prompt: "What world do you want to greet?"
      default: 30
    resource_updates:
    - type: CheckConfig
      api_version: core/v2
      name: helloworld
      fields:
      - name: metadata.name
        action: replace
        value: integration_name
      - name: spec.interval
        action: replace
        value: integration_interval
      - name: spec.command
        action: replace
        template: >-
          echo "Hello {{ .annotations.helloworld | default "[[ integration_world ]]" }} world!"
  ```

- [x] Create a template `sensu-resources.yaml` at `integrations/example/helloworld/sensu-resources.yaml` with the following contents: 

  ```yaml
  ---
  type: CheckConfig
  api_version: core/v2
  metadata:
    name: healthcheck
  spec:
    command: >-
      Hello {{ .annotations.helloworld | default "integration" }} world!
    runtime_assets: []
    publish: true
    subscriptions:
      - example
    interval: 30
    timeout: 10
    pipelines:
    - api_version: core/v2
      type: Pipeline
      name: pagerduty
  ```

- [x] Add a generic logo PNG to `integrations/example/helloworld/logo.png`
