### ISSUE TITLE
Add some severity filtering examples

### ISSUE THREAD

**Issue by calebhailey** [sensu/catalog#9]
Handlers in Sensu Core offered some built-in severity filtering. This filtering is easily reproduced in Sensu Go using something like the following: 

Only handle critical severity events: 
 
```yaml 
---
type: EventFilter 
api_version: core/v2 
metadata:
  name: critical_severity_only
spec:
  action: allow
  expressions:
  - event.check.status == 2
```

Handle critical and unknown (status 3) events only:

```yaml
---
type: EventFilter 
api_version: core/v2 
metadata:
  name: critical_severity_only
spec:
  action: allow
  expressions:
  - [2,3].includes(event.check.status)
```

Handle events that are not "OK" (0), "Warning" (1), or "Command not found" (127) status: 

```yaml
---
type: EventFilter
api_version: core/v2
metadata:
  name: filter_severities
spec: 
  action: allow
  expressions: 
  - ![0,1,127].includes(event.check.status)
```

This last example (and others like it) can be easily modified to meet almost any need from a severity filtering perspective. And the best part is these are portable and self-documenting solutions! 

_NOTE: I did not test these examples, so they should be considered as pseudo code (though they should all be pretty close to a finished product)._
